<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="omgindia244" name="com.test.ExceptionTimeOutTest" tests="2" failures="0" timestamp="19 Sep 2019 08:53:56 GMT" time="0.051" errors="1">
  <testcase name="infintLoopTest" time="0.049" classname="com.test.ExceptionTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.infintLoopTest() didn&#039;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.infintLoopTest() didn't finish within the time-out 2
]]>
    </error>
  </testcase> <!-- infintLoopTest -->
  <testcase name="test1" time="0.002" classname="com.test.ExceptionTimeOutTest"/>
</testsuite> <!-- com.test.ExceptionTimeOutTest -->
